# Generated by Django 3.0.2 on 2020-01-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresy',
            fields=[
                ('id_adres', models.IntegerField(db_column='ID_ADRES', primary_key=True, serialize=False)),
                ('miasto', models.TextField(blank=True, db_column='MIASTO', null=True)),
                ('miejscowosc', models.TextField(blank=True, db_column='MIEJSCOWOSC', null=True)),
                ('wojewodztwo', models.TextField(blank=True, db_column='WOJEWODZTWO', null=True)),
                ('powiat', models.TextField(blank=True, db_column='POWIAT', null=True)),
                ('kod_pocztowy', models.TextField(blank=True, db_column='KOD_POCZTOWY', null=True)),
                ('ulica', models.TextField(blank=True, db_column='ULICA', null=True)),
                ('nr_domu', models.TextField(blank=True, db_column='NR_DOMU', null=True)),
                ('nr_lokalu', models.TextField(blank=True, db_column='NR_LOKALU', null=True)),
            ],
            options={
                'db_table': 'ADRESY',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('last_name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('change_message', models.TextField()),
                ('action_flag', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Egzemplarze',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_egzemplarz', models.TextField(blank=True, db_column='ID_EGZEMPLARZ', null=True)),
                ('id_przedmiot', models.TextField(blank=True, db_column='ID_PRZEDMIOT', null=True)),
                ('id_zakup', models.TextField(blank=True, db_column='ID_ZAKUP', null=True)),
                ('rozmiar', models.TextField(blank=True, db_column='ROZMIAR', null=True)),
                ('kolor', models.TextField(blank=True, db_column='KOLOR', null=True)),
                ('status_egzemplarza', models.TextField(blank=True, db_column='STATUS_EGZEMPLARZA', null=True)),
            ],
            options={
                'db_table': 'EGZEMPLARZE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kontakty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_kontakt', models.TextField(blank=True, db_column='ID_KONTAKT', null=True)),
                ('nr_tel', models.TextField(blank=True, db_column='NR_TEL', null=True)),
                ('email', models.TextField(blank=True, db_column='EMAIL', null=True)),
            ],
            options={
                'db_table': 'KONTAKTY',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producenci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producent', models.TextField(blank=True, db_column='ID_PRODUCENT', null=True)),
                ('nazwa_producenta', models.TextField(blank=True, db_column='NAZWA_PRODUCENTA', null=True)),
            ],
            options={
                'db_table': 'PRODUCENCI',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Przedmioty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_przedmiot', models.TextField(blank=True, db_column='ID_PRZEDMIOT', null=True)),
                ('id_rodzaj_producent', models.TextField(blank=True, db_column='ID_RODZAJ_PRODUCENT', null=True)),
                ('zdjecia', models.TextField(blank=True, db_column='ZDJECIA', null=True)),
                ('nazwa_przedmiotu', models.TextField(blank=True, db_column='NAZWA_PRZEDMIOTU', null=True)),
                ('cena', models.TextField(blank=True, db_column='CENA', null=True)),
            ],
            options={
                'db_table': 'PRZEDMIOTY',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rodzaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_rodzaj', models.TextField(blank=True, db_column='ID_RODZAJ', null=True)),
                ('rodzaj_nazwa', models.TextField(blank=True, db_column='RODZAJ_NAZWA', null=True)),
                ('id_typ', models.TextField(blank=True, db_column='ID_TYP', null=True)),
            ],
            options={
                'db_table': 'RODZAJE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RodzajeProducenci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_rodzaj_producent', models.TextField(blank=True, db_column='ID_RODZAJ_PRODUCENT', null=True)),
                ('id_rodzaj', models.TextField(blank=True, db_column='ID_RODZAJ', null=True)),
                ('id_producent', models.TextField(blank=True, db_column='ID_PRODUCENT', null=True)),
            ],
            options={
                'db_table': 'RODZAJE_PRODUCENCI',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Uzytkownicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_uzytkownik', models.TextField(blank=True, db_column='ID_UZYTKOWNIK', null=True)),
                ('id_adres', models.TextField(blank=True, db_column='ID_ADRES', null=True)),
                ('id_kontakt', models.TextField(blank=True, db_column='ID_KONTAKT', null=True)),
                ('login', models.TextField(blank=True, db_column='LOGIN', null=True)),
                ('haslo', models.TextField(blank=True, db_column='HASLO', null=True)),
                ('imie', models.TextField(blank=True, db_column='IMIE', null=True)),
                ('nazwisko', models.TextField(blank=True, db_column='NAZWISKO', null=True)),
                ('data_zal', models.TextField(blank=True, db_column='DATA_ZAL', null=True)),
                ('role', models.TextField(blank=True, db_column='ROLE', null=True)),
            ],
            options={
                'db_table': 'UZYTKOWNICY',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zakupy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_zakup', models.TextField(blank=True, db_column='ID_ZAKUP', null=True)),
                ('id_uzytkownik', models.TextField(blank=True, db_column='ID_UZYTKOWNIK', null=True)),
                ('data_zamowienia', models.TextField(blank=True, db_column='DATA_ZAMOWIENIA', null=True)),
                ('status_zamowienia', models.TextField(blank=True, db_column='STATUS_ZAMOWIENIA', null=True)),
            ],
            options={
                'db_table': 'ZAKUPY',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Typy',
            fields=[
                ('id_typ', models.IntegerField(db_column='ID_TYP', primary_key=True, serialize=False)),
                ('typ_nazwa', models.TextField(db_column='TYP_NAZWA')),
            ],
            options={
                'db_table': 'TYPY',
                'managed': True,
            },
        ),
    ]
