# Generated by Django 3.0.2 on 2020-01-22 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklepobuwniczy', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.AlterModelOptions(
            name='adresy',
            options={},
        ),
        migrations.AlterModelOptions(
            name='egzemplarze',
            options={},
        ),
        migrations.AlterModelOptions(
            name='kontakty',
            options={},
        ),
        migrations.AlterModelOptions(
            name='producenci',
            options={},
        ),
        migrations.AlterModelOptions(
            name='przedmioty',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rodzaje',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rodzajeproducenci',
            options={},
        ),
        migrations.AlterModelOptions(
            name='typy',
            options={},
        ),
        migrations.AlterModelOptions(
            name='uzytkownicy',
            options={},
        ),
        migrations.AlterModelOptions(
            name='zakupy',
            options={},
        ),
        migrations.AlterField(
            model_name='typy',
            name='id_typ',
            field=models.AutoField(db_column='ID_TYP', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='typy',
            name='typ_nazwa',
            field=models.CharField(blank=True, db_column='TYP_NAZWA', max_length=30, null=True),
        ),
    ]
