# Generated by Django 3.0.2 on 2020-01-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklepobuwniczy', '0002_auto_20200122_0602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='egzemplarze',
            name='id',
        ),
        migrations.RemoveField(
            model_name='kontakty',
            name='id',
        ),
        migrations.RemoveField(
            model_name='producenci',
            name='id',
        ),
        migrations.RemoveField(
            model_name='przedmioty',
            name='id',
        ),
        migrations.RemoveField(
            model_name='rodzaje',
            name='id',
        ),
        migrations.RemoveField(
            model_name='rodzajeproducenci',
            name='id',
        ),
        migrations.RemoveField(
            model_name='uzytkownicy',
            name='data_zal',
        ),
        migrations.RemoveField(
            model_name='uzytkownicy',
            name='id',
        ),
        migrations.RemoveField(
            model_name='zakupy',
            name='data_zamowienia',
        ),
        migrations.RemoveField(
            model_name='zakupy',
            name='id',
        ),
        migrations.AlterField(
            model_name='adresy',
            name='id_adres',
            field=models.AutoField(db_column='ID_ADRES', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='adresy',
            name='kod_pocztowy',
            field=models.CharField(blank=True, db_column='KOD_POCZTOWY', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='adresy',
            name='miasto',
            field=models.CharField(blank=True, db_column='MIASTO', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='adresy',
            name='miejscowosc',
            field=models.CharField(blank=True, db_column='MIEJSCOWOSC', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='adresy',
            name='nr_domu',
            field=models.CharField(blank=True, db_column='NR_DOMU', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='adresy',
            name='nr_lokalu',
            field=models.CharField(blank=True, db_column='NR_LOKALU', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='adresy',
            name='powiat',
            field=models.CharField(blank=True, db_column='POWIAT', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='adresy',
            name='ulica',
            field=models.CharField(blank=True, db_column='ULICA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='adresy',
            name='wojewodztwo',
            field=models.CharField(blank=True, db_column='WOJEWODZTWO', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='egzemplarze',
            name='id_egzemplarz',
            field=models.AutoField(db_column='ID_EGZEMPLARZ', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='egzemplarze',
            name='id_przedmiot',
            field=models.IntegerField(blank=True, db_column='ID_PRZEDMIOT', null=True),
        ),
        migrations.AlterField(
            model_name='egzemplarze',
            name='id_zakup',
            field=models.IntegerField(blank=True, db_column='ID_ZAKUP', null=True),
        ),
        migrations.AlterField(
            model_name='egzemplarze',
            name='kolor',
            field=models.CharField(blank=True, db_column='KOLOR', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='egzemplarze',
            name='rozmiar',
            field=models.IntegerField(blank=True, db_column='ROZMIAR', null=True),
        ),
        migrations.AlterField(
            model_name='egzemplarze',
            name='status_egzemplarza',
            field=models.CharField(blank=True, db_column='STATUS_EGZEMPLARZA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='kontakty',
            name='email',
            field=models.CharField(blank=True, db_column='EMAIL', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='kontakty',
            name='id_kontakt',
            field=models.AutoField(db_column='ID_KONTAKT', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='kontakty',
            name='nr_tel',
            field=models.CharField(blank=True, db_column='NR_TEL', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='producenci',
            name='id_producent',
            field=models.AutoField(db_column='ID_PRODUCENT', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='producenci',
            name='nazwa_producenta',
            field=models.CharField(blank=True, db_column='NAZWA_PRODUCENTA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='przedmioty',
            name='cena',
            field=models.IntegerField(blank=True, db_column='CENA', null=True),
        ),
        migrations.AlterField(
            model_name='przedmioty',
            name='id_przedmiot',
            field=models.AutoField(db_column='ID_PRZEDMIOT', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='przedmioty',
            name='id_rodzaj_producent',
            field=models.IntegerField(blank=True, db_column='ID_RODZAJ_PRODUCENT', null=True),
        ),
        migrations.AlterField(
            model_name='przedmioty',
            name='nazwa_przedmiotu',
            field=models.CharField(blank=True, db_column='NAZWA_PRZEDMIOTU', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='przedmioty',
            name='zdjecia',
            field=models.CharField(blank=True, db_column='ZDJECIA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rodzaje',
            name='id_rodzaj',
            field=models.AutoField(db_column='ID_RODZAJ', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='rodzaje',
            name='id_typ',
            field=models.IntegerField(blank=True, db_column='ID_TYP', null=True),
        ),
        migrations.AlterField(
            model_name='rodzaje',
            name='rodzaj_nazwa',
            field=models.CharField(blank=True, db_column='RODZAJ_NAZWA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rodzajeproducenci',
            name='id_producent',
            field=models.IntegerField(blank=True, db_column='ID_PRODUCENT', null=True),
        ),
        migrations.AlterField(
            model_name='rodzajeproducenci',
            name='id_rodzaj',
            field=models.IntegerField(blank=True, db_column='ID_RODZAJ', null=True),
        ),
        migrations.AlterField(
            model_name='rodzajeproducenci',
            name='id_rodzaj_producent',
            field=models.AutoField(db_column='ID_RODZAJ_PRODUCENT', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='uzytkownicy',
            name='haslo',
            field=models.CharField(blank=True, db_column='HASLO', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='uzytkownicy',
            name='id_adres',
            field=models.IntegerField(blank=True, db_column='ID_ADRES', null=True),
        ),
        migrations.AlterField(
            model_name='uzytkownicy',
            name='id_kontakt',
            field=models.IntegerField(blank=True, db_column='ID_KONTAKT', null=True),
        ),
        migrations.AlterField(
            model_name='uzytkownicy',
            name='id_uzytkownik',
            field=models.AutoField(db_column='ID_UZYTKOWNIK', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='uzytkownicy',
            name='imie',
            field=models.CharField(blank=True, db_column='IMIE', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='uzytkownicy',
            name='login',
            field=models.CharField(blank=True, db_column='LOGIN', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='uzytkownicy',
            name='nazwisko',
            field=models.CharField(blank=True, db_column='NAZWISKO', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='uzytkownicy',
            name='role',
            field=models.CharField(blank=True, db_column='ROLE', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='zakupy',
            name='id_uzytkownik',
            field=models.IntegerField(blank=True, db_column='ID_UZYTKOWNIK', null=True),
        ),
        migrations.AlterField(
            model_name='zakupy',
            name='id_zakup',
            field=models.AutoField(db_column='ID_ZAKUP', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='zakupy',
            name='status_zamowienia',
            field=models.CharField(blank=True, db_column='STATUS_ZAMOWIENIA', max_length=30, null=True),
        ),
    ]
