# Generated by Django 3.0.2 on 2020-01-23 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklepobuwniczy', '0003_auto_20200122_1845'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Uzytkownicy',
        ),
        migrations.AlterField(
            model_name='zakupy',
            name='id_uzytkownik',
            field=models.IntegerField(blank=True, db_column='ID_UZYTKOWNIK'),
        ),
        migrations.AlterField(
            model_name='zakupy',
            name='status_zamowienia',
            field=models.CharField(blank=True, db_column='STATUS_ZAMOWIENIA', default='PRZYJETE', max_length=30),
        ),
    ]
